/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WatchHistoryIndexImport } from './routes/watch-history/index'
import { Route as TestComponentIndexImport } from './routes/test-component/index'
import { Route as PlaylistsIndexImport } from './routes/playlists/index'
import { Route as MyProfileIndexImport } from './routes/my-profile/index'
import { Route as LikedVideosIndexImport } from './routes/liked-videos/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as VideosVideoIdImport } from './routes/videos/$videoId'
import { Route as VideosPublishIndexImport } from './routes/videos/publish/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WatchHistoryIndexRoute = WatchHistoryIndexImport.update({
  id: '/watch-history/',
  path: '/watch-history/',
  getParentRoute: () => rootRoute,
} as any)

const TestComponentIndexRoute = TestComponentIndexImport.update({
  id: '/test-component/',
  path: '/test-component/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsIndexRoute = PlaylistsIndexImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRoute,
} as any)

const MyProfileIndexRoute = MyProfileIndexImport.update({
  id: '/my-profile/',
  path: '/my-profile/',
  getParentRoute: () => rootRoute,
} as any)

const LikedVideosIndexRoute = LikedVideosIndexImport.update({
  id: '/liked-videos/',
  path: '/liked-videos/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const VideosVideoIdRoute = VideosVideoIdImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRoute,
} as any)

const VideosPublishIndexRoute = VideosPublishIndexImport.update({
  id: '/videos/publish/',
  path: '/videos/publish/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/liked-videos/': {
      id: '/liked-videos/'
      path: '/liked-videos'
      fullPath: '/liked-videos'
      preLoaderRoute: typeof LikedVideosIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-profile/': {
      id: '/my-profile/'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/test-component/': {
      id: '/test-component/'
      path: '/test-component'
      fullPath: '/test-component'
      preLoaderRoute: typeof TestComponentIndexImport
      parentRoute: typeof rootRoute
    }
    '/watch-history/': {
      id: '/watch-history/'
      path: '/watch-history'
      fullPath: '/watch-history'
      preLoaderRoute: typeof WatchHistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/videos/publish/': {
      id: '/videos/publish/'
      path: '/videos/publish'
      fullPath: '/videos/publish'
      preLoaderRoute: typeof VideosPublishIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/liked-videos': typeof LikedVideosIndexRoute
  '/my-profile': typeof MyProfileIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/test-component': typeof TestComponentIndexRoute
  '/watch-history': typeof WatchHistoryIndexRoute
  '/videos/publish': typeof VideosPublishIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/liked-videos': typeof LikedVideosIndexRoute
  '/my-profile': typeof MyProfileIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/test-component': typeof TestComponentIndexRoute
  '/watch-history': typeof WatchHistoryIndexRoute
  '/videos/publish': typeof VideosPublishIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/liked-videos/': typeof LikedVideosIndexRoute
  '/my-profile/': typeof MyProfileIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/test-component/': typeof TestComponentIndexRoute
  '/watch-history/': typeof WatchHistoryIndexRoute
  '/videos/publish/': typeof VideosPublishIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/videos/$videoId'
    | '/dashboard'
    | '/liked-videos'
    | '/my-profile'
    | '/playlists'
    | '/test-component'
    | '/watch-history'
    | '/videos/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/videos/$videoId'
    | '/dashboard'
    | '/liked-videos'
    | '/my-profile'
    | '/playlists'
    | '/test-component'
    | '/watch-history'
    | '/videos/publish'
  id:
    | '__root__'
    | '/'
    | '/videos/$videoId'
    | '/dashboard/'
    | '/liked-videos/'
    | '/my-profile/'
    | '/playlists/'
    | '/test-component/'
    | '/watch-history/'
    | '/videos/publish/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LikedVideosIndexRoute: typeof LikedVideosIndexRoute
  MyProfileIndexRoute: typeof MyProfileIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  TestComponentIndexRoute: typeof TestComponentIndexRoute
  WatchHistoryIndexRoute: typeof WatchHistoryIndexRoute
  VideosPublishIndexRoute: typeof VideosPublishIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LikedVideosIndexRoute: LikedVideosIndexRoute,
  MyProfileIndexRoute: MyProfileIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  TestComponentIndexRoute: TestComponentIndexRoute,
  WatchHistoryIndexRoute: WatchHistoryIndexRoute,
  VideosPublishIndexRoute: VideosPublishIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/videos/$videoId",
        "/dashboard/",
        "/liked-videos/",
        "/my-profile/",
        "/playlists/",
        "/test-component/",
        "/watch-history/",
        "/videos/publish/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/videos/$videoId": {
      "filePath": "videos/$videoId.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/liked-videos/": {
      "filePath": "liked-videos/index.tsx"
    },
    "/my-profile/": {
      "filePath": "my-profile/index.tsx"
    },
    "/playlists/": {
      "filePath": "playlists/index.tsx"
    },
    "/test-component/": {
      "filePath": "test-component/index.tsx"
    },
    "/watch-history/": {
      "filePath": "watch-history/index.tsx"
    },
    "/videos/publish/": {
      "filePath": "videos/publish/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
